version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: web
    volumes:
      - mysql_data:/var/lib/mysql  # Используется именованный том

  php:
    build: .
    volumes:
      - ./code:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

# Определение тома на верхнем уровне
volumes:
  mysql_data:  # Том должен быть объявлен здесь